// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.DeviceUsers", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("device_mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hash")
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("device_mac");

                    b.HasIndex("user_id");

                    b.ToTable("device_users", (string)null);
                });

            modelBuilder.Entity("Models.Devices", b =>
                {
                    b.Property<string>("device_mac")
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("registered_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("device_mac");

                    b.HasIndex("user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Models.Measurement", b =>
                {
                    b.Property<Guid>("measurement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("co2")
                        .HasColumnType("double precision");

                    b.Property<string>("device_mac")
                        .HasColumnType("text");

                    b.Property<Guid>("device_users_id")
                        .HasColumnType("uuid");

                    b.Property<float?>("humidity")
                        .HasColumnType("real");

                    b.Property<float?>("temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("measurement_id");

                    b.HasIndex("device_mac");

                    b.HasIndex("device_users_id");

                    b.HasIndex("user_id");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("Models.Users", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Models.DeviceUsers", b =>
                {
                    b.HasOne("Models.Devices", null)
                        .WithMany()
                        .HasForeignKey("device_mac")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Devices", b =>
                {
                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Measurement", b =>
                {
                    b.HasOne("Models.Devices", null)
                        .WithMany()
                        .HasForeignKey("device_mac")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.DeviceUsers", null)
                        .WithMany()
                        .HasForeignKey("device_users_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
